let g:go_fmt_command = "goimports"
let g:go_info_mode='gopls'
let g:go_def_mode = 'godef'
let g:go_asmfmt_autosave = 1
let g:go_def_mapping_enabled = 1
let g:go_fmt_fail_silently = 1
let g:go_term_enabled = 1
let g:go_addtags_transform = "snakecase"
let g:go_code_completion_enabled = 1
let g:go_doc_popup_window = 1

let g:go_highlight_function_arguments=1
let g:go_highlight_function_calls = 1
let g:go_highlight_types = 1
let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_operators = 1
let g:go_highlight_build_constraints = 1
let g:go_highlight_fields = 1
let g:go_highlight_extra_types = 1
let g:go_highlight_format_strings = 1
let g:go_highlight_generate_tags = 1
let g:go_metalinter_autosave_enabled = ['vet', 'golint', 'test']
