source ~/.config/nvim/rc/base.vim
source ~/.config/nvim/rc/plug.vim
source ~/.config/nvim/rc/map.vim
source ~/.config/nvim/rc/nerd.vim
source ~/.config/nvim/rc/airline.vim
source ~/.config/nvim/rc/ycmd.vim
source ~/.config/nvim/rc/neomake.vim
source ~/.config/nvim/rc/ctrlp.vim
source ~/.config/nvim/rc/clang.vim
source ~/.config/nvim/rc/cscope_maps.vim
